<?php

namespace App\Permission;

class PermissionConst
{
    // const GESTION_MENU = 'gestion_menu';

    const GESTION_TIPO_CONTRATO    = 'GESTION_TIPO_CONTRATO';
    const GESTION_ROLES            = 'GESTION_ROLES';
    const GESTION_ROL_PERMISOS     = 'GESTION_ROL_PERMISOS';
    const GESTION_USUARIO          = 'GESTION_USUARIO';
    const GESTION_PROCESOS         = 'GESTION_PROCESOS';
    const GESTION_TIPO_DOCUMENTOS  = 'GESTION_TIPO_DOCUMENTOS';
    const GESTION_MEDIO_PAGO       = 'GESTION_MEDIO_PAGO';
    const GESTION_TIPO_PAGO        = 'GESTION_TIPO_PAGO';
    const GESTION_TIPO_TRANSACCION = 'GESTION_TIPO_TRANSACCION';

    const GESTION_COMPETENCIA = 'GESTION_COMPETENCIA';
    const GESTION_ACTIVIDAD_APRENDIZAJE = 'GESTION_ACTIVIDAD_APRENDIZAJE';
    const GESTION_RESULTADO_APRENDIZAJE = 'GESTION_RESULTADO_APRENDIZAJE';
    const GESTION_SEDE = 'GESTION_SEDE';
    const GESTION_AREA = 'GESTION_AREA';
    const GESTION_INFRAESTRUCTURA = 'GESTION_INFRAESTRUCTURA';
    const GESTION_TIPO_PROGRAMAS = 'GESTION_TIPO_PROGRAMAS';
    const GESTION_PROGRAMAS = 'GESTION_PROGRAMAS';
    const GESTION_FASES = 'GESTION_FASES';
    const GESTION_ACTIVIDAD_PROYECTO = 'GESTION_ACTIVIDAD_PROYECTO';
    const GESTION_PROYECTO_FORMATIVO = 'GESTION_PROYECTO_FORMATIVO';
    const GESTION_JORNADA          = 'GESTION_JORNADA';
    const GESTION_PAGO_NOMINA      = 'GESTION_PAGO_NOMINA';
    const GESTION_GRUPO            = 'GESTION_GRUPO'; // se crea constante de permiso GRUPO
    const GESTION_TIPO_GRUPO       = 'GESTION_TIPO_GRUPO'; // se crea constante de permiso TIPO_GRUPO
    const CALENDARIO               = 'CALENDARIO';
    const CENTRO_FORMACION         = 'CENTRO_FORMACION';
    const REGIONAL      = 'REGIONAL';
    const CARGAR_CERTIFICADOS      = 'CARGAR_CERTIFICADOS';
}
