INSERT INTO tipoTransaccion (id, detalle, descripcion) VALUES (1, 'VENTA', 'TRANSACCIONES QUE IDENTIFICA VENTAS ENTRE EL USUARIO Y EL CLIENTE');
INSERT INTO tipoTransaccion (id, detalle, descripcion) VALUES (2, 'COMPRA', 'TRANSACCIONES QUE IDENTIFICA COMPRAS ENTRE EL USUARIO Y EL PROVEEDOR');
INSERT INTO tipoTransaccion (id, detalle, descripcion) VALUES (3, 'AFILIACION', 'TRANSACCIONES QUE SE REALIZAN SOLO PARA SISTEMA Y MODULO DE AFILIACIONES');
INSERT INTO tipoTransaccion (id, detalle, descripcion) VALUES (4, 'SERVICIO', 'TRANSACCIONES QUE SE REALIZAN POR UNA PRESTACION DE SERVICIOS A LOS CLIENTES');
INSERT INTO tipoTransaccion (id, detalle, descripcion) VALUES (5, 'TRASLADO', 'TRANSACCIONES QUE SE REALIZAN ENTRE SUCURSALES DEL MISMO NEGOCIO O AREAS DE UNA EMPRESA Y APLICA ENTRE PRODUCTOS, ELEMENTOS O ARTICULOS');
